services:
  mysql8:
    container_name: sociomile-mysql
    image: mysql:8.4
    ports:
      - "3306:3306"
    volumes:
      - ./_run/mysql:/var/lib/mysql
      - ./sql:/usr/share/queries
    command: mysqld --mysql-native-password=ON
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-p$MYSQL_ROOT_PASSWORD", "-e", "SELECT 1"]
      interval: 3s
      timeout: 3s
      retries: 20
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - default

  rabbitmq:
    container_name: sociomile-rabbitmq
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./_run/rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - default

networks:
  default:
    name: sociomile-network